server:
  port: 8085
  servlet:
    context-path: /capstore
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstoreDummy
    username: root
    password: India123
  jpa:
    generate-ddl: true
    show-sql: true
    
    
    

    